name: SLSA On Move
description: SLSA On Move
branding:
  color: blue
  icon: package

inputs:
  base64-subjects:
    type: string
    required: true
  message:
    type: string
    required: true
  signature:
    type: string
    required: true

runs:
  using: node20
  main: dist/index.js
